// <auto-generated />
namespace BaseEpoch.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-alpha1")]
    public sealed partial class PeriodFlagEnum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PeriodFlagEnum));
        
        string IMigrationMetadata.Id
        {
            get { return "201611211340312_PeriodFlagEnum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
